public class Constants {
    public static final String TEST_ACCOUNT_NAME = 'Super Cars';
    public static final String TEST_CAR_NAME = 'Super fast cars';
    public static final String PICKLIST_PERSONAL_CARS = 'Personal Cars';
    public static final String PICKLIST_AVAILABLE = 'Available at the showroom';
    public static final String PICKLIST_AVAILABLE_AT_DIFFERENT = 'Available at different showroom';
    public static final String PICKLIST_TEMPERATURE = 'Temperature';
    public static final String PICKLIST_ROTATION_SPEED = 'Rotation speed';
    public static final String PICKLIST_CLOSED = 'Closed';
    public static final String FULL_SHOWROOM_ERROR = 'Cannot add a new car because the showroom is full!';
    public static final String ALREADY_AVAILABLE_ERROR = 'The car offer is already available at the showroom';
    public static final String NOT_IN_SHOWROOM_ERROR = 'The car is not in selected showroom';
    public static final String THERE_ALREADY_IS_WAREHOUSE_ERROR = 'Account of this showroom already has a warehouse: ';
    public static final String CANNOT_CLOSE_ERROR = 'Cannot close because there are cars left in the showroom';
    public static final String LESS_THAN_ZERO_ERROR = 'Number of car spaces cannot be less then 0!';
    public static final String LESS_THAN_CARS_AVAILABLE_ERROR = 'Number of car spaces cannot be less then number of cars available at the showroom!';
}