public class Constants {
    public static final String testAccountName = 'Super Cars';
    public static final String testCarName = 'Super fast cars';
    public static final String picklistPersonalCars = 'Personal Cars';
    public static final String picklistAvailable = 'Available at the showroom';
    public static final String picklistAvailableAtDifferent = 'Available at different showroom';
    public static final String picklistTemperature = 'Temperature';
    public static final String picklistRotationSpeed = 'Rotation speed';
    public static final String picklistClosed = 'Closed';
    public static final String fullShowroomError = 'Cannot add a new car because the showroom is full!';
    public static final String alreadyAvailableError = 'The car offer is already available at the showroom';
    public static final String notInShowroomError = 'The car is not in selected showroom';
    public static final String thereAlreadyIsWarehouseError = 'Account of this showroom already has a warehouse: ';
    public static final String cannotCloseError = 'Cannot close because there are cars left in the showroom';
    public static final String lessThanZeroError = 'Number of car spaces cannot be less then 0!';
    public static final String lessThanCarsAvailableError = 'Number of car spaces cannot be less then number of cars available at the showroom!';
}